[package]
name = "kg-symbol"
version = "0.1.3"
description = "Atomic strings in Rust"
authors = ["Jakub Chłapiński <jakub.chlapinski@kodegenix.pl>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/Kodegenix/kg-symbol.rs"

[dependencies]
lazy_static = "1.1"
heapsize = "0.4"
serde = "1.0"

[dev-dependencies]
serde_json = "1.0"
