[package]
name = "kg-symbol"
version = "0.1.0"
authors = ["Jakub Chłapiński <jakub.chlapinski@kodegenix.pl>"]

[dependencies]
lazy_static = "1.1"
heapsize = "0.4"
serde = "1.0"

[dev-dependencies]
serde_json = "1.0"
